apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eddc94l6h-go
  janus-idp.io/tekton: eddc94l6h-go
  backstage.io/kubernetes-id: eddc94l6h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eddc94l6h-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
