apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eddc94l6h-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eddc94l6h-go 
  name: eddc94l6h-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eddc94l6h-go 
